// Generated by auto-env. Do not update manually

export const MODE = "dev";
export const DEV = true;
export const PORT = 8000;
export const RATE_LIMIT = 500;
export const URL = "http://localhost:8000";
export const GREETING = "Hello, World!";
export const OPTIONAL_FLAG = undefined;
export const ALSO_EMPTY = "";
export const PRIVATE_KEY = `
-----BEGIN EC KEY-----
MHQCAQEEIBkg...
-----END EC KEY-----`;
