import type { StandardSchemaV1 } from "@standard-schema/spec";
import { dirname } from "@std/path";
import { type EnvValueType, parse } from "./parser.ts";

/**
 * Environment variable configuration
 */
export type EnvVarConfig = {
  /**
   * Variable description for documentation on hover
   */
  description?: string;
  /**
   * Whether the variable is public
   *
   * - If `true`, can be imported from the public env module `.env.public.ts`
   * - If `false`, can be imported from the prive env module `.env.private.ts`
   *
   * @default false
   */
  public?: boolean;
  /**
   * A standard schema to validate the variable
   */
  schema?: StandardSchemaV1;
};

/**
 * Environment variables config
 *
 * A key-value record with keys matching your environment
 */
export type AutoEnvConfig = Record<string, EnvVarConfig>;

/**
 * {@link autoEnv} global options
 */
export type Options = {
  /**
   * The path to your .env file
   *
   * @default ".env"
   */
  inputPath?: string;
  /**
   * The output path to the generated public env module
   *
   * Set to `null` to not emit the file
   *
   * @default ".generated/env.public.ts"
   */
  publicOutputPath?: string | undefined | null;
  /**
   * The output path to the generated private env module
   *
   * Set to `null` to not emit the file
   *
   * * @default ".generated/env.private.ts"
   */
  privateOutputPath?: string | undefined | null;
  /**
   * Granular configuration Record. The keys correspond to your env keys you can provide it with a `EnvVarConfig` object for custom validation with a standard schema or control whether it is public or private
   *
   * @example
   * ```ts
   * import * as v from "valibot";
   *
   * await autoEnv({
   *    config: {
   *      EMAIL: { schema: v.pipe(v.string(), v.email()) },
   *    },
   * });
   *
   * ```
   */
  config?: AutoEnvConfig;
};

async function parseEnvFile(
  path: string,
): Promise<[string, EnvValueType][]> {
  const textFile = await Deno.readTextFile(path);
  return parse(textFile);
}

async function validateEnv(
  inputValue: EnvValueType,
  config?: EnvVarConfig,
): Promise<unknown> {
  const schema = config?.schema;
  if (!schema) return inputValue;

  const result = await schema["~standard"].validate(inputValue);

  if (result.issues) {
    const message = result.issues[0]?.message ?? "[auto-env]: Validation error";
    throw new ValidationError(message);
  }

  return result.value;
}

class ValidationError {
  message: string;

  constructor(message: string) {
    this.message = message;
  }
}

async function validateEnvs(
  options: { keyValuePairs: [string, EnvValueType][]; config?: AutoEnvConfig },
) {
  const publicEnvs = new Map();
  const privateEnvs = new Map();

  for (const [key, stringValue] of options.keyValuePairs) {
    const envConfig = options.config?.[key];
    try {
      const value = await validateEnv(stringValue, envConfig);

      (envConfig?.public)
        ? publicEnvs.set(key, value)
        : privateEnvs.set(key, value);
    } catch (error) {
      if (error instanceof ValidationError) {
        throw new Error(
          `[auto-env] Validation error with key "${key}". ${error.message}`,
          { cause: error },
        );
      }

      throw new Error(`[auto-env] Parse error. ${error}`, { cause: error });
    }
  }

  return { publicEnvs, privateEnvs };
}

const newLine = /\n/;

function tsMultilineComment(content: string) {
  return `
/**
 * ${content}
 */
`;
}

function generateModuleText(
  data: Map<string, unknown>,
  config?: AutoEnvConfig,
) {
  let moduleText = "// Generated by auto-env. Do not update manually\n\n";

  for (const [key, value] of data.entries()) {
    const jsValue = typeof value === "string"
      ? newLine.test(value) ? "`" + value + "`" : '"' + value + '"'
      : value;

    const description = config?.[key]?.description;

    moduleText += description ? tsMultilineComment(description) : "";
    moduleText += `export const ${key} = ${jsValue};\n`;
  }

  return moduleText;
}

const PUBLIC_OUTPUT_DEFAULT = ".env.public.ts";
const PRIVATE_OUTPUT_DEFAULT = ".env.private.ts";

/**
 * Define and configure your environment variables
 */
export async function autoEnv(options?: Options): Promise<{
  publicModuleText: string;
  privateModuleText: string;
}> {
  console.log("[auto-env]: generating env modules");

  const config = options?.config;
  const inputPath = options?.inputPath ?? ".env";
  const envs = await parseEnvFile(inputPath);

  // Ensure all keys of the config object match an environment variable key
  const keys = envs.map(([k]) => k);
  for (const key of Object.keys(config ?? {})) {
    if (!keys.includes(key)) {
      throw new Error(
        `[auto-env]: config key "${key}" not found in env file at "${inputPath}". Is this a typo?`,
      );
    }
  }

  const { publicEnvs, privateEnvs } = await validateEnvs({
    keyValuePairs: envs,
    config,
  });

  const publicModuleText = generateModuleText(publicEnvs, config);
  const privateModuleText = generateModuleText(privateEnvs, config);

  const publicOutputPath = options?.publicOutputPath === undefined
    ? PUBLIC_OUTPUT_DEFAULT
    : options?.publicOutputPath;

  if (publicModuleText) {
    publicOutputPath
      ? await writeTextFile(publicOutputPath, publicModuleText)
      : console.log("[auto-env]: no public output path provided. Skipping...");
  }

  const privateOutputPath = options?.privateOutputPath === undefined
    ? PRIVATE_OUTPUT_DEFAULT
    : options?.privateOutputPath;

  if (privateModuleText) {
    privateOutputPath
      ? await writeTextFile(privateOutputPath, privateModuleText)
      : console.log("[auto-env]: no private output path provided. Skipping...");
  }

  return { publicModuleText, privateModuleText };
}

async function writeTextFile(path: string, data: string) {
  await Deno.mkdir(dirname(path), { recursive: true });
  await Deno.writeTextFile(path, data, { create: true });
}
