// Generated by auto-env. Do not update manually

export const DEV = true;
export const DEV_STRING = "true";
export const PORT = 3000;
export const PORT_STRING = "3000";
export const REGEX = "\d{3}-\d{4}";
export const OPTIONAL_FLAG = undefined;
export const ALSO_EMPTY = "";
export const PRIVATE_KEY = `
-----BEGIN EC KEY-----
MHQCAQEEIBkg...
-----END EC KEY-----`;
