import { ERROR_MESSAGE, PREFIX } from "$/src/constants.ts";
import { parseEnvFile } from "$/src/parse.ts";
import { validateEnvs } from "$/src/validate.ts";
import type { StandardSchemaV1 } from "@standard-schema/spec";
import { dirname } from "@std/path";

/**
 * Environment variable configuration
 */
export type EnvVarConfig = {
  /**
   * Variable description for documentation on hover
   */
  description?: string;
  /**
   * Whether the variable is public
   *
   * - If `true`, can be imported from the public env module `.env.public.ts`
   * - If `false`, can be imported from the prive env module `.env.private.ts`
   *
   * @default false
   */
  public?: boolean;
  /**
   * A standard schema to validate the variable
   */
  schema?: StandardSchemaV1;
};

/**
 * Environment variables config
 *
 * A key-value record with keys matching your environment
 */
export type AutoEnvConfig = Record<string, EnvVarConfig>;

/**
 * {@link autoEnv} global options
 */
export type Options = {
  /**
   * The path to your .env file
   *
   * @default ".env"
   */
  inputPath?: string;
  /**
   * The output path to the generated public env module
   *
   * Set to `null` to not emit the file
   *
   * @default ".generated/env.public.ts"
   */
  publicOutputPath?: string | undefined | null;
  /**
   * The output path to the generated private env module
   *
   * Set to `null` to not emit the file
   *
   * * @default ".generated/env.private.ts"
   */
  privateOutputPath?: string | undefined | null;
  /**
   * Environment variable configuration record. Keys correspond to your env keys. Values can be an {@linkcode EnvVarConfig} object
   *
   * @example
   * ```ts
   * import * as v from "valibot";
   *
   * await autoEnv({
   *    config: {
   *      EMAIL: { schema: v.pipe(v.string(), v.email()) },
   *    },
   * });
   *
   * ```
   */
  config?: AutoEnvConfig;
};

const newLine = /\n/;

function tsMultilineComment(content: string) {
  return `/**
 * ${content}
 */
`;
}

function generateModuleText(
  data: Map<string, unknown>,
  config?: AutoEnvConfig,
) {
  let moduleText = "// Generated by auto-env. Do not update manually\n\n";

  for (const [key, value] of data.entries()) {
    const jsValue = typeof value === "string"
      ? newLine.test(value) ? "`" + value + "`" : '"' + value + '"'
      : value;

    const description = config?.[key]?.description;

    moduleText += description ? tsMultilineComment(description) : "";
    moduleText += `export const ${key} = ${jsValue};\n`;
  }

  return moduleText;
}

const PUBLIC_OUTPUT_DEFAULT = ".env.public.ts";
const PRIVATE_OUTPUT_DEFAULT = ".env.private.ts";

/**
 * Reads and validates your environment variables
 * Outputs TypeScript modules for type-safe env imports
 */
export async function autoEnv(options?: Options): Promise<{
  publicModuleText: string;
  privateModuleText: string;
}> {
  console.log(PREFIX + "Generating env modules");

  const config = options?.config;
  const inputPath = options?.inputPath ?? ".env";
  const envs = await parseEnvFile(inputPath);

  // Ensure all keys of the config object match an environment variable key
  const keys = envs.map(([k]) => k);
  for (const key of Object.keys(config ?? {})) {
    if (!keys.includes(key)) {
      throw new Error(ERROR_MESSAGE.UnmatchedKey(key, inputPath));
    }
  }

  const { publicEnvs, privateEnvs } = await validateEnvs({
    keyValuePairs: envs,
    config,
  });

  const publicModuleText = generateModuleText(publicEnvs, config);
  const privateModuleText = generateModuleText(privateEnvs, config);

  const publicOutputPath = options?.publicOutputPath === undefined
    ? PUBLIC_OUTPUT_DEFAULT
    : options?.publicOutputPath;

  if (publicModuleText) {
    publicOutputPath
      ? await writeTextFile(publicOutputPath, publicModuleText)
      : console.log(PREFIX + "No public output path provided. Skipping...");
  }

  const privateOutputPath = options?.privateOutputPath === undefined
    ? PRIVATE_OUTPUT_DEFAULT
    : options?.privateOutputPath;

  if (privateModuleText) {
    privateOutputPath
      ? await writeTextFile(privateOutputPath, privateModuleText)
      : console.log(PREFIX + "No private output path provided. Skipping...");
  }

  return { publicModuleText, privateModuleText };
}

async function writeTextFile(path: string, data: string) {
  await Deno.mkdir(dirname(path), { recursive: true });
  await Deno.writeTextFile(path, data, { create: true });
}
